# Generated by Django 5.0.7 on 2024-07-13 10:48

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[756, 741], upload_to='slider/%Y/%m')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'db_table': 'slider',
            },
        ),
    ]
