# Generated by Django 5.0.7 on 2024-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_projectcategory_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='project is top'),
        ),
    ]
