# Generated by Django 5.0.7 on 2024-07-16 10:27

import django.utils.timezone
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_project_is_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_large',
        ),
        migrations.AddField(
            model_name='project',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=django.utils.timezone.now, force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[370, 379], upload_to='projects/%Y/%m', verbose_name='image'),
            preserve_default=False,
        ),
    ]
