# Generated by Django 5.0.7 on 2024-07-16 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_project_image_large_alter_project_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
