# Generated by Django 5.0.7 on 2024-07-23 10:16

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog categories',
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'blog tag',
                'verbose_name_plural': 'blog tags',
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('is_top', models.BooleanField(default=False, verbose_name='category is top')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(max_length=256, verbose_name='author')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[540, 304], upload_to='blog/%Y/%m', verbose_name='main image')),
                ('large_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[1100, 700], upload_to='blog/%Y/%m', verbose_name='large image')),
                ('read_time', models.IntegerField(verbose_name='read time')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('categories', models.ManyToManyField(related_name='blogs', to='common.blogcategory', verbose_name='categories')),
                ('tags', models.ManyToManyField(related_name='blogs', to='common.blogtag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('comment', models.TextField(verbose_name='comment')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.blog', verbose_name='blog')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.blogcomment', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'blog comment',
                'verbose_name_plural': 'blog comments',
                'db_table': 'blog_comment',
            },
        ),
    ]
