# Generated by Django 5.0.7 on 2024-07-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_blogcategory_blogtag_blog_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='blog is top'),
        ),
    ]
