# Generated by Django 5.0.7 on 2024-08-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
