# Generated by Django 5.0.7 on 2024-08-29 11:07

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_projectcategory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_large',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=None, size=[1100, 700], upload_to='projects/%Y/%m', verbose_name='image large'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=None, size=[370, 379], upload_to='projects/%Y/%m', verbose_name='image small'),
        ),
    ]
